### ISSUE TITLE
min lenght and number filtering not working

### ISSUE THREAD

**Issue by nesjett** [Donatello-za/rake-php-plus#15]
This code is not working:
```

$rake = RakePlus::create($text, $locale, 3, true);
$phrases = $rake->sortByScore('desc')->keywords();
```

I get shorter than 3 characters keywords and some of them are only numbers.

Not sure what the issue may be.

LANGUAGE: **es_AR**

Thank you,
- Nesjett

**Comment by Donatello-za** [comment]
Hi, the character limitation and number filtering were originally intended for phrases only, e.g.
```php
$rake = RakePlus::create($text, $locale, 3, true);
$phrases = $rake->sortByScore('desc')->get();  // This returns phrases (instead of keywords)
```

However, I've changed the keywords() function to also implement the same filtering and it should work now as you expected in v.1.0.11.
