### ISSUE TITLE
Additional languages

### ISSUE THREAD

**Issue by spekulatius** [Donatello-za/rake-php-plus#22]
If anyone is in need of a currently unsupported language it might be interesting to check this: https://github.com/Linguistic/stopwords. Just adding this as an issue so other have it easier finding potential stopword lists.

**Comment by spekulatius** [comment]
@Donatello-za do you think we could pin this to the issues in case someone needs it?

**Comment by Donatello-za** [comment]
Hi @spekulatius, at the bottom of the documentation there is a section called [How to add additional languages](https://github.com/Donatello-za/rake-php-plus#how-to-add-additional-languages) under which there is a link to stopwords for other languages, see it here: https://github.com/Donatello-za/stopwords-json

**Comment by spekulatius** [comment]
Ah okay, I forgot about this. Lists looking pretty good - I guess we can close this one then, right?

**Comment by Donatello-za** [comment]
No problem, with the next release I may add a section to the top of the documentation to just make it clear that you can add your own stopwords and that you can look at the bottom of the docs for more details on how to and where to get the stopwords files from.

**Comment by spekulatius** [comment]
Good idea @Donatello-za
