### ISSUE TITLE
Keywords with hyphens (-) are split again

### ISSUE THREAD

**Issue by arnaudbroes** [Donatello-za/rake-php-plus#30]
Hey @Donatello-za,

I believe this issue might be back - https://github.com/Donatello-za/rake-php-plus/issues/9

See screenshot below - 

![image](https://user-images.githubusercontent.com/18156697/144766186-ab890eb5-feeb-4d92-b717-fd1ebf8e21f8.png)

Would you be able to confirm this for me? I'm happy to take a look at the code and see if I can figure it out in case you're too busy.

**Comment by Donatello-za** [comment]
Hi @arnaudbroes, I'll take a look at it, thanks for reporting it.

**Comment by Donatello-za** [comment]
I've added a test case to my local development branch specifically to test the word zync-plated and it seems to handle it just fine. Are you sure you are on version 1.0.7 or later? This issue was addressed in version 1.0.7 back in December 2018.

**Comment by arnaudbroes** [comment]
@Donatello-za totally my bad, I was on 1.0.0 even though I only started using this package a few months ago. Thank you for checking, I appreciate it, and my apologies for the nuisance.

**Comment by Donatello-za** [comment]
> @Donatello-za totally my bad, I was on 1.0.0 even though I only started using this package a few months ago. Thank you for checking, I appreciate it, and my apologies for the nuisance.

No problem man, it is better to just check it out anyway. I was sure the unit tests would've picked it up if the bug returned but you never know right? :)
