### ISSUE TITLE
mb_eregi_replace UTF-8 encoding in RakePlus.php on line 384

### ISSUE THREAD

**Issue by severfire** [Donatello-za/rake-php-plus#35]
Hello,

First, thanks for all your work!

I do have one issue... 
When using Swedish language I get error:

PHP Warning:  mb_eregi_replace(): Pattern is not valid under UTF-8 encoding in /vendor/donatello-za/rake-php-plus/src/RakePlus.php on line 384

How can I fix it?

Thanks!
a.

**Comment by severfire** [comment]
Google Gemini suggests:

The error message "PHP Warning: mb_eregi_replace(): Pattern is not valid under UTF-8 encoding" indicates an issue with the `mb_eregi_replace` function call in the `RakePlus.php` file (line 384) of the RAKE-PHP-Plus library. Here's how to fix it:

**Understanding the Error:**

- `mb_eregi_replace` is a deprecated function for regular expression operations with multibyte characters (like UTF-8). It's prone to errors and has security vulnerabilities.
- The error suggests the provided pattern for string replacement might contain invalid characters or be improperly encoded for UTF-8.

**Solution:**

**1. Upgrade RAKE-PHP-Plus (Recommended):**

The most straightforward solution is to upgrade the RAKE-PHP-Plus library. The developers might have already addressed this issue in newer versions. Update your composer dependencies by running:

```bash
composer update donatello-za/rake-php-plus
```

This will fetch the latest version of the library and potentially include bug fixes or replacements for `mb_eregi_replace`.

**2. Use `mb_ereg_replace` (Temporary Fix):**

If upgrading isn't feasible immediately, you can temporarily replace `mb_eregi_replace` with `mb_ereg_replace`. However, this function is also deprecated and not recommended for long-term use:

**Original:**

```php
// (In RakePlus.php, line 384)
$cleanString = mb_eregi_replace($pattern, '', $string);
```

**Replacement:**

```php
// (In RakePlus.php, line 384 - Temporary fix)
$cleanString = mb_ereg_replace($pattern, '', $string);
```

**3. Switch to `preg_replace` (Recommended Approach):**

If upgrading or using `mb_ereg_replace` isn't an option, consider switching to the recommended `preg_replace` function with the `u` modifier:

**Replacement:**

```php
// (In RakePlus.php, line 384)
$cleanString = preg_replace($pattern, '', $string, -1, PREG_UNICODE);
```

- `preg_replace` is the modern and secure way for regular expression replacements in PHP.
- The `u` modifier (PREG_UNICODE) ensures proper UTF-8 handling.
- The `-1` argument (optional) removes all occurrences of the pattern (default behavior of `mb_eregi_replace`).

**Important Notes:**

- **Testing:** Make sure to thoroughly test your code after any modifications to ensure the intended behavior is maintained.
- **Long-Term Solution:** Upgrading the library is the most sustainable solution to address potential issues and benefit from security patches.

By implementing one of these solutions, you should be able to resolve the error and perform correct string replacements within the RAKE-PHP-Plus library.

**Comment by Donatello-za** [comment]
@severfire, thanks for the bug report.

Can you please specify the PHP version you are using and the string that you are passing through that is causing the error?

Thanks!

**Comment by severfire** [comment]
PHP version is 8.2

and string would be combined

https://www.garageportexperten.se/
https://www.garageportexperten.se/om-oss/
https://www.garageportexperten.se/portar/
https://garageportexperten.se/montage-underhall/
https://garageportexperten.se/kontakt/

scraped h1, h2, h3, h4 and meta description with Crwlr\Crawler\Crawler
unfortunately I do not have currently exact string

**Comment by Donatello-za** [comment]
I basically just need to be able to replicate the error/warning, can you perhaps provide me with some of the raw crawling data?

**Comment by severfire** [comment]
for all of those i am getting 
Warning: mb_eregi_replace(): Pattern is not valid under UTF-8 encoding in C:\xampp\htdocs\app\vendor\donatello-za\rake-php-plus\src\RakePlus.php on line 384

title string: 
Garageportar, ytterdörrar och tillbehör | Garageportexperten

description string:
Garageportar från Sveriges ledande leverantörer som GPE, Crawford, Edsbyn, Dieden och Hörmann. Vi har Sveriges bredaste sortiment och erbjuder självklart även

h1 string: 
DET DU GÖR EN GÅNG I LIVET. GÖR VI VARJE DAG.

h2 string: 
Varukorg. Allt i ett - SOMMARPAKETET. Boka ett gratis hembesök för att se vilken port som passar ditt garage bäst.. Vi monterar i hela Sverige.. Vi hjälper dig – hela vägen. Portsimulatorn. Ett bra montage är avgörande för hur värmebeständig porten blir.. Läs mer om service & underhåll här. Boka ett gratis hembesök så hjälper vi dig med mätning och val av ny port. Boka ett gratis hembesök för att se vilken port som passar ditt garage bäst.. Vad är ett hembesök?. Experter som tipsar. Så väljer du en energismart garageport

h3 string: 
{{ $get(lang, 'CartError.Title', 'Ojdå! Något gick fel.') }}. {{ $get(lang, 'EmptyCart.Title', 'Din varukorg är tom!') }}. Portar. Dörrar. Montage & underhåll. Butiker. Portguiden. Garageportar. Tillbehör. Industriportar. Dörrar. Tillbehör. Om montaget. Service & underhåll. Anpassa garaget. Butiker. När du ska välja.... Portkategorier. Inspiration. Expertens tips. Höstens favoriter. Bostadsrättsföreningar. Industriportar. Tips och manualer för port, motor eller fjärrkontroll. Precis som att bilen behöver servas och skorstenen sotas, behöver också din garageport regelbunden service och underhåll för att den ska få de bästa förutsättningarna att hålla i många år framöver. Det blir klimatsmart, säkert och kostnadseffektivt. . För täta utrymmen kan leda till fukt och svartmögel. Välj från ett brett urval av energieffektiva garageportar

h4  string: 
Garageportar. Tillbehör. Industriportar. Dörrar. Tillbehör. Om montaget. Service & underhåll. Anpassa garaget. Butiker. . . När du ska välja.... Portkategorier. Inspiration. Expertens tips. Höstens favoriter. Bostadsrättsföreningar. Industriportar. Tips och manualer för port, motor eller fjärrkontroll. Sverigeporten+ - Kassett. Sverigeporten+ - S-Profil. Sverigeporten+ - L-Profil. Sverigeporten+ - M-Profil. Sverigeporten+ - Macrorib. Sverigeporten+ - L-Profil. Sverigeporten+ - M-Profil. Sverigeporten+ - M-Profil. Huvudkontor. Facebook

**Comment by Donatello-za** [comment]
Thanks, much appreciated!

**Comment by severfire** [comment]
Thank you, let me know if I can help in any way.

**Comment by Donatello-za** [comment]
Ok, after testing those input strings you provided I could not replicate the error using PHP 8.2 and 8.3. However, I have a feeling that since the package up to this point didn't officially supported the Swedish language you created your own stopwords pattern? If so I have a feeling that the pattern you provide for the stop words is formatted incorrectly which causes the exception.

That being said, I have just released `v1.0.19` and added the Swedish language/stopwords which effectively means the package officially supports Swedish (svenska). Once you've upgraded the package try instantiating it with the `sv_SE` stopwords file, for Example:

```php
$text = 'Garageportar, ytterdörrar och tillbehör | Garageportexperten';
$keywords = RakePlus::create($text, 'sv_SE')->keywords();
print_r($keywords);

Array
(
    [0] => garageportar
    [1] => ytterdörrar
    [2] => tillbehör
    [3] => garageportexperten
)
```

If it is still giving errors, do the following:
1. Make sure your are using the new release: `v.1.0.19`.
2. Are you using Linux? If so it may help if you setup the Swedish language locale, for example in Ubuntu 22.04 you can do the following:
```sh
sudo locale-gen sv_SE
sudo locale-gen sv_SE.utf8
```
Let me know if you are successful or not.

**Comment by severfire** [comment]
Yes, I do have custom language files for Swedish, Norwegian etc, done based on specs you provided. I will check encoding for them. Thank you.

**Comment by severfire** [comment]
You are right, extractor made it UTF-16 like the original files or something went above my understanding. Its worth checking or/and updating extractor so it could format to UTF-8. I changed my files from UTF-16 to UTF-8.  I hope it will work well now. Thank you!

**Comment by Donatello-za** [comment]
Thanks for your feedback, I appreciate it. I would like to try and figure out how the file ended up as a UTF-16 file and to either document how to get around the problem or perhaps how to convert the pattern if it is UTF-16 encoded. I have a feeling that if you are on Linux it might be due to you're current locale settings. 

Would you mind running the `locale` command in your terminal and paste the results for me here? For example, mine looks like this:
```
$ locale
LANG=en_ZA.UTF-8
LANGUAGE=en_ZA:en
LC_CTYPE="en_ZA.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME="en_ZA.UTF-8"
LC_COLLATE="en_ZA.UTF-8"
LC_MONETARY=C
LC_MESSAGES="en_ZA.UTF-8"
LC_PAPER="en_ZA.UTF-8"
LC_NAME="en_ZA.UTF-8"
LC_ADDRESS="en_ZA.UTF-8"
LC_TELEPHONE="en_ZA.UTF-8"
LC_MEASUREMENT="en_ZA.UTF-8"
LC_IDENTIFICATION="en_ZA.UTF-8"
LC_ALL=
```
