### ISSUE TITLE
Problem with encoding in special chars

### ISSUE THREAD

**Issue by tematres** [Donatello-za/rake-php-plus#4]
There are any requirement to parse special char? I have some problems to parse words with special chars.
Here stps to reproduce:
1) URL
http://www.vocabularyserver.com/test/apps/termdistiller/index.php
2) Sample text: Cámara Federal de Casación Penal

3) results: casaci�n penal, c�mara federal
(sorry about my english).

**Comment by Donatello-za** [comment]
Hi, I have just released a new version with better multibyte character support (v1.0.5) that fixes a number of bugs. However, your problem may not be related to this package but instead a mismatch between your PHP output and your browser. Please see:
* https://stackoverflow.com/questions/275411/php-output-showing-little-black-diamonds-with-a-question-mark
* https://stackoverflow.com/questions/39023215/character-encoding-issues-php

**Comment by tematres** [comment]
Fantastic!! the problem was solved with multibyte support!. Thank you!

**Comment by Donatello-za** [comment]
Thanks for your feedback!
